services:
  squidarr-proxy:
    image: ghcr.io/mgthepro/squidarr-proxy:main
    container_name: squidarr-proxy
    environment:
      - TZ=Europe/Berlin
      - DOWNLOAD_PATH=/data/squidarr
      - CATEGORY=music
      - REGION=eu
      - PORT=8687
      # The API Key is the password to your instance, set when configuring indexer and downloader in Lidarr
      # Set any value you wish here, but do not leave it empty
      - API_KEY=
    user: "1000:1000"
    volumes:
      - ./downloads/folder/here:/data/squidarr
    ports:
      - "8687:8687"
    restart: unless-stopped
