services:
  squidarr-proxy:
    image: squidarr-proxy:latest
    container_name: squidarr-proxy
    environment:
      - TZ=Europe/Berlin
      - DOWNLOAD_PATH=/data/squidarr
      - CATEGORY=music
      - REGION=eu
      - PORT=8687
    volumes:
      - ./downloads/folder/here:/data/squidarr
    ports:
      - "8687:8687"
    restart: unless-stopped
